### ISSUE TITLE
Gulp build issue in server

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Node.Prototype#49]
When I try and build the server I get the following issues:
```
➜  glimpse.server git:(master) gulp build
[17:35:20] Using gulpfile ~/Projects/Glimpse.Node.Prototype/src/glimpse.server/gulpfile.js
[17:35:20] Starting 'build-typescript'...
[17:35:20] Starting 'build-javascript'...
[17:35:20] Starting 'build-embedded'...
[17:35:34] Finished 'build-embedded' after 14 s
[BABEL] Note: The code generator has deoptimised the styling of "/Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/resources/node_modules/acorn/dist/acorn.js" as it exceeds the max of "100KB".

events.js:141
      throw er; // Unhandled 'error' event
      ^
SyntaxError: /Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/resources/node_modules/async-listener/test/native-promises.tap.js: 'return' outside of function (1:21)
> 1 | if (!global.Promise) return;
    |                      ^
  2 |
  3 | var test = require('tap').test;
  4 |
    at Parser.pp.raise (/Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/node_modules/babylon/index.js:1425:13)
    at Parser.pp.parseReturnStatement (/Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/node_modules/babylon/index.js:2094:10)
    at Parser.pp.parseStatement (/Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/node_modules/babylon/index.js:1894:19)
    at Parser.pp.parseIfStatement (/Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/node_modules/babylon/index.js:2087:26)
    at Parser.pp.parseStatement (/Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/node_modules/babylon/index.js:1892:19)
    at Parser.pp.parseBlockBody (/Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/node_modules/babylon/index.js:2294:21)
    at Parser.pp.parseTopLevel (/Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/node_modules/babylon/index.js:1823:8)
    at Parser.parse (/Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/node_modules/babylon/index.js:1396:17)
    at Object.parse (/Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/node_modules/babylon/index.js:45:50)
    at File.parse (/Users/anthonyvanderhoorn/Projects/Glimpse.Node.Prototype/src/glimpse.server/node_modules/babel-core/lib/transformation/file/index.js:480:24)
```

Note, my npm dependencies are up to date.

**Comment by philliphoff** [comment]
It looks like you somehow ended up with a `node_modules` subfolder in your `src/glimpse.server/resources` folder which is likely why Babel is attempting to compile the scripts within it.

The `node_modules` folder isn't in the repo, and I don't see similar build errors locally.

**Comment by avanderhoorn** [comment]
As far as I know, you user settings will override the workspace settings. So if you were doing some work that required knowledge of these, you could alway undo them just for your context.
